"""add pending_messages queue table

Revision ID: afdab7fcffe1
Revises: 6faf31916c51
Create Date: 2026-08-23 11:45:43.292413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afdab7fcffe1'
down_revision: Union[str, Sequence[str], None] = '6faf31916c51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_messages_created_at'), 'pending_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_pending_messages_user_id'), 'pending_messages', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_messages_user_id'), table_name='pending_messages')
    op.drop_index(op.f('ix_pending_messages_created_at'), table_name='pending_messages')
    op.drop_table('pending_messages')
    # ### end Alembic commands ###
